### ISSUE TITLE
[Crash] Error: java.lang.NoClassDefFoundError: javafx/util/Pair Exit Code: -1

### ISSUE THREAD

**Issue by J-Wildfire-T** [SuperMartijn642/ChunkLoaders#10]
**Version Info**
- Minecraft, 1.12.2
- Chunk Loaders, 1.1.5

**Steps to Reproduce**
Place one basic loader in the overworld and one in the netherworld.
Save and exit game.
Close launcher.
Load launcher.
Load game.
Crash occurs.

**Crash report (~/logs/latest.log)**
[21:23:03] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:23:03] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:23:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:23:03] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[21:23:03] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at E:\Minecraft\runtime\jre-x64
[21:23:03] [main/INFO] [FML]: Searching C:\Users\*omitted*\AppData\Roaming\.minecraft\mods for mods
[21:23:03] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:23:03] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:23:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:23:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:23:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:23:05] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[21:23:05] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[21:23:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:23:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:23:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:23:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:23:05] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[21:23:05] [Client thread/INFO] [net.minecraft.client.Minecraft]: Setting user: *omitted*
[21:23:07] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[21:23:07] [Client thread/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[21:23:07] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 777101784 bytes (741 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
[21:23:07] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2854 Initialized
[21:23:07] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[21:23:07] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[21:23:07] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[21:23:08] [Client thread/INFO] [FML]: Searching C:\Users\*omitted*\AppData\Roaming\.minecraft\mods for mods
[21:23:08] [Client thread/INFO] [FML]: Forge Mod Loader has identified 7 mods to load
[21:23:08] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, chunkloaders, jei, supermartijn642configlib] at CLIENT
[21:23:08] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, chunkloaders, jei, supermartijn642configlib] at SERVER
[21:23:09] [Client thread/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Chunk Loaders, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:SuperMartijn642's Config Library
[21:23:09] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[21:23:09] [Client thread/INFO] [FML]: Found 1172 ObjectHolder annotations
[21:23:09] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[21:23:09] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[21:23:09] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[21:23:09] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[21:23:09] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `single_chunk_loader_tile`, expected `chunkloaders`. This could be a intended override, but in most cases indicates a broken mod.
[21:23:09] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `basic_chunk_loader_tile`, expected `chunkloaders`. This could be a intended override, but in most cases indicates a broken mod.
[21:23:09] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `advanced_chunk_loader_tile`, expected `chunkloaders`. This could be a intended override, but in most cases indicates a broken mod.
[21:23:09] [Client thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `ultimate_chunk_loader_tile`, expected `chunkloaders`. This could be a intended override, but in most cases indicates a broken mod.
[21:23:09] [Client thread/INFO] [FML]: Applying holder lookups
[21:23:09] [Client thread/INFO] [FML]: Holder lookups applied
[21:23:09] [Client thread/INFO] [FML]: Applying holder lookups
[21:23:09] [Client thread/INFO] [FML]: Holder lookups applied
[21:23:09] [Client thread/INFO] [FML]: Applying holder lookups
[21:23:09] [Client thread/INFO] [FML]: Holder lookups applied
[21:23:09] [Client thread/INFO] [FML]: Applying holder lookups
[21:23:09] [Client thread/INFO] [FML]: Holder lookups applied
[21:23:09] [Client thread/INFO] [FML]: Injecting itemstacks
[21:23:09] [Client thread/INFO] [FML]: Itemstack injection complete
[21:23:09] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: UP_TO_DATE Target: null
[21:23:09] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[21:23:09] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[21:23:09] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:23:09] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[21:23:10] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 14999800 nanos
[21:23:10] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[21:23:10] [Client thread/INFO] [FML]: Max texture size: 16384
[21:23:11] [Client thread/INFO] [net.minecraft.client.renderer.texture.TextureMap]: Created: 512x512 textures-atlas
[21:23:12] [Client thread/INFO] [FML]: Applying holder lookups
[21:23:12] [Client thread/INFO] [FML]: Holder lookups applied
[21:23:12] [Client thread/INFO] [jei]: Created: 256x128 textures-atlas
[21:23:12] [Client thread/INFO] [FML]: Injecting itemstacks
[21:23:12] [Client thread/INFO] [FML]: Itemstack injection complete
[21:23:12] [Client thread/INFO] [jei]: Starting JEI...
[21:23:12] [Client thread/INFO] [jei]: Registering recipe categories...
[21:23:12] [Client thread/INFO] [jei]: Registering recipe categories took 9.671 ms
[21:23:12] [Client thread/INFO] [jei]: Registering mod plugins...
[21:23:12] [Client thread/INFO] [jei]: Registering mod plugins took 79.83 ms
[21:23:12] [Client thread/INFO] [jei]: Building recipe registry...
[21:23:12] [Client thread/INFO] [jei]: Building recipe registry took 30.63 ms
[21:23:12] [Client thread/INFO] [jei]: Building ingredient list...
[21:23:12] [Client thread/INFO] [jei]: Building ingredient list took 12.41 ms
[21:23:12] [Client thread/INFO] [jei]: Building ingredient filter...
[21:23:12] [Client thread/INFO] [jei]: Building ingredient filter took 41.08 ms
[21:23:12] [Client thread/INFO] [jei]: Building bookmarks...
[21:23:12] [Client thread/INFO] [jei]: Building bookmarks took 2.996 ms
[21:23:12] [Client thread/INFO] [jei]: Building runtime...
[21:23:12] [Client thread/INFO] [jei]: Building runtime took 46.43 ms
[21:23:12] [Client thread/INFO] [jei]: Optimizing memory usage...
[21:23:12] [Client thread/INFO] [jei]: Optimizing memory usage took 19.55 ms
[21:23:12] [Client thread/INFO] [jei]: Starting JEI took 324.3 ms
[21:23:12] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 7 mods
[21:23:12] [Client thread/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[21:23:12] [Client thread/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded
[21:23:20] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Starting integrated minecraft server version 1.12.2
[21:23:20] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Generating keypair
[21:23:20] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[21:23:20] [Server thread/INFO] [FML]: Applying holder lookups
[21:23:20] [Server thread/INFO] [FML]: Holder lookups applied
[21:23:20] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@2701e470)
[21:23:21] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 488 advancements
[21:23:21] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: javafx/util/Pair
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$ChunkTracker.read(ChunkLoaderUtil.java:181) ~[ChunkLoaderUtil$ChunkTracker.class:?]
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$1.readNBT(ChunkLoaderUtil.java:48) ~[ChunkLoaderUtil$1.class:?]
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$1.readNBT(ChunkLoaderUtil.java:40) ~[ChunkLoaderUtil$1.class:?]
	at net.minecraftforge.common.capabilities.Capability.readNBT(Capability.java:102) ~[Capability.class:?]
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$2.deserializeNBT(ChunkLoaderUtil.java:77) ~[ChunkLoaderUtil$2.class:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:135) ~[CapabilityDispatcher.class:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:45) ~[CapabilityDispatcher.class:?]
	at net.minecraftforge.common.util.WorldCapabilityData.setCapabilities(WorldCapabilityData.java:74) ~[WorldCapabilityData.class:?]
	at net.minecraft.world.World.initCapabilities(World.java:3988) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:173) ~[oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:122) ~[chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 14 more
Caused by: java.lang.NullPointerException
[21:23:21] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Users\*omitted*\AppData\Roaming\.minecraft\crash-reports\crash-2021-02-08_21.23.21-server.txt
[21:23:21] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[21:23:21] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[21:23:21] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[21:23:21] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/overworld
[21:23:21] [Server thread/INFO] [FML]: Unloading dimension 0
[21:23:21] [Server thread/INFO] [FML]: Applying holder lookups
[21:23:21] [Server thread/INFO] [FML]: Holder lookups applied
[21:23:21] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
[21:23:21] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/8/21 9:23 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: javafx/util/Pair
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$ChunkTracker.read(ChunkLoaderUtil.java:181)
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$1.readNBT(ChunkLoaderUtil.java:48)
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$1.readNBT(ChunkLoaderUtil.java:40)
	at net.minecraftforge.common.capabilities.Capability.readNBT(Capability.java:102)
	at com.supermartijn642.chunkloaders.ChunkLoaderUtil$2.deserializeNBT(ChunkLoaderUtil.java:77)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:135)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:45)
	at net.minecraftforge.common.util.WorldCapabilityData.setCapabilities(WorldCapabilityData.java:74)
	at net.minecraft.world.World.initCapabilities(World.java:3988)
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:173)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:122)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 240543360 bytes (229 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version      | Source                                    | Signature                                |
	|:------ |:------------------------ |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp                      | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML                      | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | supermartijn642configlib | 1.0.4        | supermartijn642configlib-1.0.4-mc1.12.jar | None                                     |
	| LCHIJA | chunkloaders             | 1.1.5        | chunkloaders-1.1.5-mc1.12.jar             | None                                     |
	| LCHIJA | jei                      | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar                 | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[21:23:21] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed!

**Comment by SuperMartijn642** [comment]
I fixed it now in 1.1.6.

Thanks for reporting the issue!
