### ISSUE TITLE
[Bug] Exception while loading entries for entrypoint 'jade' provided by 'chunkloaders'

### ISSUE THREAD

**Issue by gkr0013** [SuperMartijn642/ChunkLoaders#103]
Dear,

On server Minecraft 1.20.1 with Fabric Loader 0.14.21, with chunkloaders v1.2.7, there are somme errors with Jade (Jade-1.20-fabric-11.5.1). Already test with differents versions on minecraft 1.20.1, always this error.

[11:00:05] [Server thread/ERROR]: Error loading plugin at null
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'jade' provided by 'chunkloaders'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.14.21.jar:?]
	at snownee.jade.util.CommonProxy.lambda$loadComplete$5(CommonProxy.java:338) ~[Jade-1.20-fabric-11.5.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at snownee.jade.util.CommonProxy.loadComplete(CommonProxy.java:333) ~[Jade-1.20-fabric-11.5.1.jar:?]
	at snownee.jade.util.CommonProxy.lambda$onInitialize$10(CommonProxy.java:392) ~[Jade-1.20-fabric-11.5.1.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-d192667b6fe65399.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zmn000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:3342) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: com.supermartijn642.entangled.integration.EntangledWailaPlugin
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.supermartijn642.entangled.integration.EntangledWailaPlugin
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
	... 9 more

Thanks

**Comment by SuperMartijn642** [comment]
Seems I missed this in the 1.19.4 and 1.20 branches. It should be fixed now in Chunk Loaders version 1.2.7a.

Thank you for reporting the issue!
