### ISSUE TITLE
[Crash] The game crashes whenever I open a chunk loader and select a chunk

### ISSUE THREAD

**Issue by Blackberrycak3** [SuperMartijn642/ChunkLoaders#117]
**Im playing 1.16.5**
- Minecraft, Works fine without the mod
- Chunk Loaders, are causing my game to crash

**Are you using OptiFine? *Yes*

**Steps to Reproduce**
...

**Crash report (~/logs/latest.log)**
...<html>
<body>

---- Minecraft Crash Report ----
--
2 | // Why did you do that?
3 |  
4 | Time: 3/11/24 10:20 PM
5 | Description: Exception in server tick loop
6 |  
7 | java.lang.NoSuchMethodError: net.minecraft.world.server.TicketManager.registerTicking(Lnet/minecraft/world/server/TicketType;Lnet/minecraft/util/math/ChunkPos;ILjava/lang/Object;)V
8 | at net.minecraft.world.server.ServerChunkProvider.registerTickingTicket(ServerChunkProvider.java:438) ~[?:?] {re:classloading,pl:accesstransformer:B}
9 | at net.minecraftforge.common.world.ForgeChunkManager.forceChunk(ForgeChunkManager.java:158) ~[?:?] {re:classloading}
10 | at net.minecraftforge.common.world.ForgeChunkManager.forceChunk(ForgeChunkManager.java:138) ~[?:?] {re:classloading}
11 | at net.minecraftforge.common.world.ForgeChunkManager.forceChunk(ForgeChunkManager.java:101) ~[?:?] {re:classloading}
12 | at com.supermartijn642.chunkloaders.capability.ServerChunkLoadingCapability.loadChunk(ServerChunkLoadingCapability.java:188) ~[?:?] {re:classloading}
13 | at com.supermartijn642.chunkloaders.capability.ServerChunkLoadingCapability.startLoadingChunk(ServerChunkLoadingCapability.java:114) ~[?:?] {re:classloading}
14 | at com.supermartijn642.chunkloaders.packet.PacketToggleChunk.handle(PacketToggleChunk.java:55) ~[?:?] {re:classloading}
15 | at com.supermartijn642.core.network.PacketChannel.lambda$handle$8(PacketChannel.java:226) ~[?:?] {re:classloading}
16 | at com.supermartijn642.core.network.PacketChannel$$Lambda$7493/1535377534.run(Unknown Source) ~[?:?] {}
17 | at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:201) ~[?:?] {re:classloading}
18 | at com.supermartijn642.core.network.PacketContext.queueTask(PacketContext.java:48) ~[?:?] {re:classloading}
19 | at com.supermartijn642.core.network.PacketChannel.handle(PacketChannel.java:226) ~[?:?] {re:classloading}
20 | at com.supermartijn642.core.network.PacketChannel.access$300(PacketChannel.java:26) ~[?:?] {re:classloading}
21 | at com.supermartijn642.core.network.PacketChannel$InternalPacket.handle(PacketChannel.java:243) ~[?:?] {re:classloading}
22 | at com.supermartijn642.core.network.PacketChannel.lambda$new$3(PacketChannel.java:80) ~[?:?] {re:classloading}
23 | at com.supermartijn642.core.network.PacketChannel$$Lambda$3175/1395912847.accept(Unknown Source) ~[?:?] {}
24 | at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) ~[?:?] {re:classloading}
25 | at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$7126/2119725420.accept(Unknown Source) ~[?:?] {}
26 | at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
27 | at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) ~[?:?] {re:classloading}
28 | at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[?:?] {re:classloading}
29 | at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66) ~[?:?] {re:classloading}
30 | at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$3007/1014698874.accept(Unknown Source) ~[?:?] {}
31 | at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
32 | at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
33 | at net.minecraftforge.eventbus.EventBus$$Lambda$3009/748523772.invoke(Unknown Source) ~[?:?] {}
34 | at net.minecraftforge.eventbus.EventBus$$Lambda$3334/1370668231.invoke(Unknown Source) ~[?:?] {}
35 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
36 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
37 | at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72) ~[?:?] {re:classloading}
38 | at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:77) ~[?:?] {re:classloading}
39 | at net.minecraftforge.fml.network.NetworkHooks$$Lambda$7114/1639264530.apply(Unknown Source) ~[?:?] {}
40 | at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
41 | at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:77) ~[?:?] {re:classloading}
42 | at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?] {re:classloading}
43 | at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading}
44 | at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading}
45 | at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:classloading,xf:OptiFine:default}
46 | at net.minecraft.network.PacketThreadUtil$$Lambda$7197/11255917.run(Unknown Source) ~[?:?] {}
47 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
48 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
49 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
50 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
51 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
52 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
53 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
54 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
55 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:150) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
56 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
57 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
58 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
59 | at net.minecraft.server.MinecraftServer$$Lambda$6117/421948579.run(Unknown Source) [?:?] {}
60 | at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
61 |  
62 |  
63 | A detailed walkthrough of the error, its code path and all known details is as follows:
64 | ---------------------------------------------------------------------------------------
65 |  
66 | -- System Details --
67 | Details:
68 | Minecraft Version: 1.16.5
69 | Minecraft Version ID: 1.16.5
70 | Operating System: Windows 10 (amd64) version 10.0
71 | Java Version: 1.8.0_51, Oracle Corporation
72 | Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
73 | Memory: 1613127888 bytes (1538 MB) / 3271557120 bytes (3120 MB) up to 4294967296 bytes (4096 MB)
74 | CPUs: 12
75 | JVM Flags: 9 total; -XX: UnlockExperimentalVMOptions -XX: UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX: IgnoreUnrecognizedVMOptions
76 | ModLauncher: 8.1.3 8.1.3 main-8.1.x.c94d18ec
77 | ModLauncher launch target: fmlclient
78 | ModLauncher naming: srg
79 | ModLauncher services:
80 | /mixin-0.8.4.jar mixin PLUGINSERVICE
81 | /eventbus-4.0.0.jar eventbus PLUGINSERVICE
82 | /forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE
83 | /forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE
84 | /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE
85 | /forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE
86 | /forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE
87 | /mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE
88 | /OptiFine_1.16.5_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE
89 | /forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE
90 | FML: 36.2
91 | Forge: net.minecraftforge:36.2.39
92 | FML Language Providers:
93 | javafml@36.2
94 | minecraft@1
95 | Mod List:
96 | forge-1.16.5-36.2.39-client.jar                   \|Minecraft                     \|minecraft                     \|1.16.5              \|DONE      \|Manifest: NOSIGNATURE
97 | Statues-1.16.5-0.1.7.7.jar                        \|Statues Mod                   \|statues                       \|**.**.**.**             \|DONE      \|Manifest: NOSIGNATURE
98 | supermartijn642configlib-1.1.8-forge-mc1.16.jar   \|SuperMartijn642's Config Libra\|supermartijn642configlib      \|1.1.8               \|DONE      \|Manifest: NOSIGNATURE
99 | worldedit-mod-7.2.5-dist.jar                      \|WorldEdit                     \|worldedit                     \|7.2.5 57d5ac9       \|DONE      \|Manifest: NOSIGNATURE
100 | scarecrowsterritory-1.1.11-forge-mc1.16.jar       \|Scarecrows' Territory         \|scarecrowsterritory           \|1.1.11              \|DONE      \|Manifest: NOSIGNATURE
101 | jei-1.16.5-7.7.1.153.jar                          \|Just Enough Items             \|jei                           \|**.**.**.**           \|DONE      \|Manifest: NOSIGNATURE
102 | supermartijn642corelib-1.1.17a-forge-mc1.16.jar   \|SuperMartijn642's Core Lib    \|supermartijn642corelib        \|1.1.17a             \|DONE      \|Manifest: NOSIGNATURE
103 | chunkloaders-1.2.8a-forge-mc1.16.jar              \|Chunk Loaders                 \|chunkloaders                  \|1.2.8a              \|DONE      \|Manifest: NOSIGNATURE
104 | caelus-forge-1.16.5-2.1.3.2.jar                   \|Caelus API                    \|caelus                        \|1.16.5-2.1.3.2      \|DONE      \|Manifest: NOSIGNATURE
105 | forge-1.16.5-36.2.39-universal.jar                \|Forge                         \|forge                         \|36.2.39             \|DONE      \|Manifest: ****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****
106 | colytra-forge-1.16.5-5.1.1.2.jar                  \|Colytra                       \|colytra                       \|1.16.5-5.1.1.2      \|DONE      \|Manifest: NOSIGNATURE
107 | durabilitytooltip-1.1.5-forge-mc1.16.jar          \|Durability Tooltip            \|durabilitytooltip             \|1.1.5               \|DONE      \|Manifest: NOSIGNATURE
108 | journeymap-1.16.5-5.8.5p6.jar                     \|Journeymap                    \|journeymap                    \|5.8.5p6             \|DONE      \|Manifest: NOSIGNATURE
109 | ironchest-1.16.5-11.2.21.jar                      \|Iron Chests                   \|ironchest                     \|1.16.5-11.2.21      \|DONE      \|Manifest: NOSIGNATURE
110 | replaymod-1.16.4-2.6.15.jar                       \|Replay Mod                    \|replaymod                     \|2.5.1               \|DONE      \|Manifest: NOSIGNATURE
111 | Crash Report UUID: c128aafd-dcf6-4341-b13a-2f1199433dce
112 | Player Count: 1 / 8; [ServerPlayerEntity['Blackberrycak3'/95, l='ServerLevel[main world]', x=785.77, y=71.74, z=38.03]]
113 | Data Packs: vanilla, mod:forge, mod:worldedit (incompatible), mod:journeymap (incompatible), mod:ironchest, mod:jei, mod:caelus, mod:colytra (incompatible), mod:supermartijn642corelib, mod:supermartijn642configlib, mod:durabilitytooltip, mod:scarecrowsterritory, mod:replaymod, mod:statues, mod:chunkloaders
114 | Type: Integrated Server (map_client.txt)
115 | Is Modded: Definitely; Client brand changed to 'forge'
116 | OptiFine Version: OptiFine_1.16.5_HD_U_G6
117 | OptiFine Build: 20210117-013236
118 | Render Distance Chunks: 8
119 | Mipmaps: 4
120 | Anisotropic Filtering: 1
121 | Antialiasing: 0
122 | Multitexture: false
123 | Shaders: null
124 | OpenGlVersion: 4.6.0 Compatibility Profile Context 23.11.1.231017
125 | OpenGlRenderer: AMD Radeon(TM) Graphics
126 | OpenGlVendor: ATI Technologies Inc.
127 | CpuCount: 12

</body>
</html>
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/11/[2](https://mclo.gs/rhiahnG#L2)4 10:20 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.server.TicketManager.registerTicking(Lnet/minecraft/world/server/TicketType;Lnet/minecraft/util/math/ChunkPos;ILjava/lang/Object;)V
	at net.minecraft.world.server.ServerChunkProvider.registerTickingTicket(ServerChunkProvider.java:4[3](https://mclo.gs/rhiahnG#L3)8) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.common.world.ForgeChunkManager.forceChunk(ForgeChunkManager.java:158) ~[?:?] {re:classloading}
	at net.minecraftforge.common.world.ForgeChunkManager.forceChunk(ForgeChunkManager.java:138) ~[?:?] {re:classloading}
	at net.minecraftforge.common.world.ForgeChunkManager.forceChunk(ForgeChunkManager.java:101) ~[?:?] {re:classloading}
	at com.supermartijn6[4](https://mclo.gs/rhiahnG#L4)2.chunkloaders.capability.ServerChunkLoadingCapability.loadChunk(ServerChunkLoadingCapability.java:188) ~[?:?] {re:classloading}
	at com.supermartijn642.chunkloaders.capability.ServerChunkLoadingCapability.startLoadingChunk(ServerChunkLoadingCapability.java:114) ~[?:?] {re:classloading}
	at com.supermartijn642.chunkloaders.packet.PacketToggleChunk.handle(PacketToggleChunk.java:[5](https://mclo.gs/rhiahnG#L5)5) ~[?:?] {re:classloading}
	at com.supermartijn[6](https://mclo.gs/rhiahnG#L6)42.core.network.PacketChannel.lambda$handle$8(PacketChannel.java:226) ~[?:?] {re:classloading}
	at com.supermartijn642.core.network.PacketChannel$$Lambda$[7](https://mclo.gs/rhiahnG#L7)493/1535377534.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:201) ~[?:?] {re:classloading}
	at com.supermartijn642.core.network.PacketContext.queueTask(PacketContext.java:4[8](https://mclo.gs/rhiahnG#L8)) ~[?:?] {re:classloading}
	at com.supermartijn642.core.network.PacketChannel.handle(PacketChannel.java:226) ~[?:?] {re:classloading}
	at com.supermartijn642.core.network.PacketChannel.access$300(PacketChannel.java:26) ~[?:?] {re:classloading}
	at com.supermartijn642.core.network.PacketChannel$InternalPacket.handle(PacketChannel.java:243) ~[?:?] {re:classloading}
	at com.supermartijn642.core.network.PacketChannel.lambda$new$3(PacketChannel.java:80) ~[?:?] {re:classloading}
	at com.supermartijn642.core.network.PacketChannel$$Lambda$3175/13[9](https://mclo.gs/rhiahnG#L9)5912847.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$7126/2119725420.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$3007/[10](https://mclo.gs/rhiahnG#L10)14698874.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$[11](https://mclo.gs/rhiahnG#L11)(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3009/748523772.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3334/1370668231.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:77) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$7114/1639264530.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:77) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:[12](https://mclo.gs/rhiahnG#L12)) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$7197/11255917.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_2[13](https://mclo.gs/rhiahnG#L13)166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:[15](https://mclo.gs/rhiahnG#L15)9) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213[16](https://mclo.gs/rhiahnG#L16)8_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:7[17](https://mclo.gs/rhiahnG#L17)) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:150) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6117/421948579.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1613127888 bytes (1538 MB) / 3271557120 bytes (3120 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX: UnlockExperimentalVMOptions -XX: UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX: IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3 8.1.3 main-8.1.x.c94d[18](https://mclo.gs/rhiahnG#L18)ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		Statues-1.16.5-0.1.7.7.jar                        |Statues Mod                   |statues                       |**.**.**.**             |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.16.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.5-dist.jar                      |WorldEdit                     |worldedit                     |7.2.5 57d5ac9       |DONE      |Manifest: NOSIGNATURE
		scarecrowsterritory-1.1.11-forge-mc1.16.jar       |Scarecrows' Territory         |scarecrowsterritory           |1.1.11              |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.153.jar                          |Just Enough Items             |jei                           |**.**.**.**           |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17a-forge-mc1.16.jar   |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17a             |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.2.8a-forge-mc1.16.jar              |Chunk Loaders                 |chunkloaders                  |1.2.8a              |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.2.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.2      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: ****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****:****
		colytra-forge-1.16.5-5.1.1.2.jar                  |Colytra                       |colytra                       |1.16.5-5.1.1.2      |DONE      |Manifest: NOSIGNATURE
		durabilitytooltip-1.1.5-forge-mc1.16.jar          |Durability Tooltip            |durabilitytooltip             |1.1.5               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p6.jar                     |Journeymap                    |journeymap                    |5.8.5p6             |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |DONE      |Manifest: NOSIGNATURE
		replaymod-1.16.4-2.6.15.jar                       |Replay Mod                    |replaymod                     |2.5.1               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: c128aafd-dcf6-4341-b13a-2f1[19](https://mclo.gs/rhiahnG#L19)9433dce
	Player Count: 1 / 8; [ServerPlayerEntity['Blackberrycak3'/95, l='ServerLevel[main world]', x=785.77, y=71.74, z=38.03]]
	Data Packs: vanilla, mod:forge, mod:worldedit (incompatible), mod:journeymap (incompatible), mod:ironchest, mod:jei, mod:caelus, mod:colytra (incompatible), mod:supermartijn642corelib, mod:supermartijn642configlib, mod:durabilitytooltip, mod:scarecrowsterritory, mod:replaymod, mod:statues, mod:chunkloaders
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: [20](https://mclo.gs/rhiahnG#L20)[21](https://mclo.gs/rhiahnG#L21)0117-013[23](https://mclo.gs/rhiahnG#L23)6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 23.11.1.2[31](https://mclo.gs/rhiahnG#L31)017
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by SuperMartijn642** [comment]
This is caused by OptiFine overwriting Forge added methods. Nothing I can do about this. Either update OptiFine or if that doesn't work, don't use it at all.
