### ISSUE TITLE
[Question] chunk loader in fabric server

### ISSUE THREAD

**Issue by Ryuaaz** [SuperMartijn642/ChunkLoaders#85]
**Question**
...
i put the chunk loader mod on the mods folder on my server and start the server 
and this is the message i get :
 ( Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[12:30:56] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[12:30:56] [ForkJoinPool-1-worker-2/WARN]: Mod chunkloaders uses the version 1.2.3b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '3b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:30:56] [main/WARN]: Mod resolution failed
[12:30:56] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE supermartijn642corelib 1.1.7 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE supermartijn642corelib 1.1.7]
[12:30:56] [main/INFO]: Reason: [HARD_DEP chunkloaders 1.2.3b {depends fabric @ [*]}, HARD_DEP supermartijn642corelib 1.1.7 {depends fabric @ [*]}, HARD_DEP supermartijn642configlib 1.1.6 {depends fabric @ [*]}]
[12:30:56] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)])], remove [], replace []
[12:30:56] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install fabric, any version.
Unmet dependency listing:
         - Mod 'Chunk Loaders' (chunkloaders) 1.2.3b requires any version of fabric, which is missing!
         - Mod 'SuperMartijn642's Core Lib' (supermartijn642corelib) 1.1.7 requires any version of fabric, which is missing!
         - Mod 'SuperMartijn642's Config Lib' (supermartijn642configlib) 1.1.6 requires any version of fabric, which is missing!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.19.jar:?] )

please help :L

**Comment by SuperMartijn642** [comment]
You need to install Fabric API.
