### ISSUE TITLE
[Crash] ...right click  open GUI

### ISSUE THREAD

**Issue by nico1972weimar** [SuperMartijn642/ChunkLoaders#95]
Minecraft Version: 1.20.1
Minecraft Version ID: 1.20.1
Operating System: Windows 10 (amd64) version 10.0
Java Version: 17.0.3, Microsoft
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft

- Chunk Loaders, ...
Chunk Loaders 1.2.5
**Are you using OptiFine?:**  No

**Steps to Reproduce**
place a chunkloader on the World and right click on the placed chunkloader crashed game

**Crash report (~/logs/latest.log)**
[14:03:01] [main/INFO]: ModLauncher running: args [--username, Nico1972Weimar, --version, forge-47.1.3, --gameDir, C:\Users\Nico\curseforge\minecraft\Instances\All the Mods 9 - ATM9, --assetsDir, C:\Users\Nico\curseforge\minecraft\Install\assets, --assetIndex, 5, --uuid, XXXXXXXXXXXXXdbcd, --accessToken, ????????, --clientId, ZTJiYzg4MDktNGVjNi00ODQ3LWI1YzYtMjUzZWQ0YmVmN2Zl, --xuid, 2535424814608532, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 47.1.3, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[14:03:01] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[14:03:03] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[14:03:03] [main/INFO]: Trying GL version 4.6
[14:03:03] [main/INFO]: Requested GL version 4.6 got version 4.6
[14:03:04] [pool-2-thread-1/INFO]: GL info: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.40, NVIDIA Corporation

[14:08:30] [Render thread/ERROR]: Exception caught during firing event: Already building!
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.anthonyhilyard.legendarytooltips.LegendaryTooltips onPostTooltipEvent(Lcom/anthonyhilyard/iceberg/events/RenderTooltipExtEvent$Post;)V
java.lang.IllegalStateException: Already building!
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.vertex.BufferBuilder.m_166779_(BufferBuilder.java:100)
	at TRANSFORMER/iceberg@1.1.12/com.anthonyhilyard.iceberg.util.GuiHelper.drawGradientRect(GuiHelper.java:24)
	at TRANSFORMER/legendarytooltips@1.4.4/com.anthonyhilyard.legendarytooltips.tooltip.TooltipDecor.drawShadow(TooltipDecor.java:78)
	at TRANSFORMER/legendarytooltips@1.4.4/com.anthonyhilyard.legendarytooltips.LegendaryTooltips.onPostTooltipEvent(LegendaryTooltips.java:261)
	at TRANSFORMER/legendarytooltips@1.4.4/com.anthonyhilyard.legendarytooltips.__LegendaryTooltips_onPostTooltipEvent_Post.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.GuiGraphics.handler$cnb000$icebergRenderTooltipInternalPost(GuiGraphics.java:1769)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.GuiGraphics.m_280497_(GuiGraphics.java:633)
	at TRANSFORMER/supermartijn642corelib@1.1.9/com.supermartijn642.core.gui.ScreenUtils.drawTooltipInternal(ScreenUtils.java:297)
	at TRANSFORMER/supermartijn642corelib@1.1.9/com.supermartijn642.core.gui.ScreenUtils.drawTooltip(ScreenUtils.java:264)
	at TRANSFORMER/supermartijn642corelib@1.1.9/com.supermartijn642.core.gui.ScreenUtils.drawTooltip(ScreenUtils.java:276)
	at TRANSFORMER/supermartijn642corelib@1.1.9/com.supermartijn642.core.gui.widget.BaseWidget.renderTooltips(BaseWidget.java:170)
	at TRANSFORMER/supermartijn642corelib@1.1.9/com.supermartijn642.core.gui.widget.BaseWidget.renderTooltips(BaseWidget.java:165)
	at TRANSFORMER/supermartijn642corelib@1.1.9/com.supermartijn642.core.gui.widget.BaseWidget.renderTooltips(BaseWidget.java:165)
	at TRANSFORMER/supermartijn642corelib@1.1.9/com.supermartijn642.core.gui.WidgetScreen.m_88315_(WidgetScreen.java:85)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[14:08:31] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[14:08:31] [Render thread/INFO]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[14:08:31] [Render thread/INFO]: Stopping JEI
[14:08:31] [Render thread/INFO]: Sending Runtime Unavailable...
[14:08:31] [Render thread/INFO]: Stopping JEI GUI
[14:08:31] [Render thread/INFO]: Sending Runtime Unavailable took 2.593 ms
[14:08:31] [Render thread/INFO]: Released client Flux Networks cache
[14:08:32] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:978) ~[client-1.20.1-20230612.114412-srg.jar%23700!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23700!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23700!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.IllegalStateException: Already building!
	at com.mojang.blaze3d.vertex.BufferBuilder.m_166779_(BufferBuilder.java:100) ~[client-1.20.1-20230612.114412-srg.jar%23700!/:?]
	at com.anthonyhilyard.iceberg.util.GuiHelper.drawGradientRect(GuiHelper.java:24) ~[Iceberg-1.20.1-forge-1.1.12.jar%23556!/:1.1.12]
	at com.anthonyhilyard.legendarytooltips.tooltip.TooltipDecor.drawShadow(TooltipDecor.java:78) ~[LegendaryTooltips-1.20.1-forge-1.4.4.jar%23575!/:1.4.4]
	at com.anthonyhilyard.legendarytooltips.LegendaryTooltips.onPostTooltipEvent(LegendaryTooltips.java:261) ~[LegendaryTooltips-1.20.1-forge-1.4.4.jar%23575!/:1.4.4]
	at com.anthonyhilyard.legendarytooltips.__LegendaryTooltips_onPostTooltipEvent_Post.invoke(.dynamic) ~[LegendaryTooltips-1.20.1-forge-1.4.4.jar%23575!/:1.4.4]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraft.client.gui.GuiGraphics.handler$cnb000$icebergRenderTooltipInternalPost(GuiGraphics.java:1769) ~[client-1.20.1-20230612.114412-srg.jar%23700!/:?]
	at net.minecraft.client.gui.GuiGraphics.m_280497_(GuiGraphics.java:633) ~[client-1.20.1-20230612.114412-srg.jar%23700!/:?]
	at com.supermartijn642.core.gui.ScreenUtils.drawTooltipInternal(ScreenUtils.java:297) ~[supermartijn642corelib-1.1.9-forge-mc1.20.jar%23671!/:?]
	at com.supermartijn642.core.gui.ScreenUtils.drawTooltip(ScreenUtils.java:264) ~[supermartijn642corelib-1.1.9-forge-mc1.20.jar%23671!/:?]
	at com.supermartijn642.core.gui.ScreenUtils.drawTooltip(ScreenUtils.java:276) ~[supermartijn642corelib-1.1.9-forge-mc1.20.jar%23671!/:?]
	at com.supermartijn642.core.gui.widget.BaseWidget.renderTooltips(BaseWidget.java:170) ~[supermartijn642corelib-1.1.9-forge-mc1.20.jar%23671!/:?]
	at com.supermartijn642.core.gui.widget.BaseWidget.renderTooltips(BaseWidget.java:165) ~[supermartijn642corelib-1.1.9-forge-mc1.20.jar%23671!/:?]
	at com.supermartijn642.core.gui.widget.BaseWidget.renderTooltips(BaseWidget.java:165) ~[supermartijn642corelib-1.1.9-forge-mc1.20.jar%23671!/:?]
	at com.supermartijn642.core.gui.WidgetScreen.m_88315_(WidgetScreen.java:85) ~[supermartijn642corelib-1.1.9-forge-mc1.20.jar%23671!/:?]
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23700!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.3-universal.jar%23705!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.3-universal.jar%23705!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23700!/:?]
	... 18 more
[14:08:32] [Render thread/FATAL]: Preparing crash report with UUID 75ad0284-06df-433a-9d14-4561b9071252
[14:08:32] [Render thread/FATAL]: Preparing crash report with UUID e2f5678d-7596-412f-868d-1a0b8e0b4be9

**Comment by AHilyard** [comment]
I've received the same report from a user of Legendary Tooltips here: https://github.com/AHilyard/LegendaryTooltips/issues/100

In investigating the issue, I've discovered that there is a similar problem with other mods that use supermartijn642corelib (such as Rechiseled).  
@SuperMartijn642 I've done some testing and found that this crash can be avoided by passing the original vanilla GuiGraphics instance from Minecraft's rendering methods into your renderTooltipInternal method instead of creating your own instance.  I can make a PR if you'd prefer, but I don't want to mess up any of your other mods that may be using your tooltip functionality.

**Comment by SuperMartijn642** [comment]
I changed it so it uses the same buffer source as the regular gui, so should be fixed now in version 1.1.12a of my core library.
Thanks for reporting the issue and thanks for the help 😊

**Comment by nico1972weimar** [comment]
Thanks for fixing the error so quickly
